const actionMovies = [
    {
      name: 'The Dark Knight',
      length: '2h 32m',
      protagonist: 'Christian Bale',
      releaseDate: '2008',
      rating: 9,
      description: 'A brooding crime thriller where Batman faces off against the Joker in a battle for Gotham City.',
    },
    {
      name: 'Die Hard',
      length: '2h 12m',
      protagonist: 'Bruce Willis',
      releaseDate: '1988',
      rating: 8,
      description: 'A New York cop battles a group of terrorists who take hostages in a Los Angeles skyscraper during a Christmas party.',
    },
    {
      name: 'John Wick',
      length: '1h 41m',
      protagonist: 'Keanu Reeves',
      releaseDate: '2014',
      rating: 8,
      description: 'A retired hitman seeks vengeance against those who wronged him and killed his dog.',
    },
    {
      name: 'Mad Max: Fury Road',
      length: '2h',
      protagonist: 'Tom Hardy',
      releaseDate: '2015',
      rating: 8,
      description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland.',
    },
    {
      name: 'Mission: Impossible - Fallout',
      length: '2h 27m',
      protagonist: 'Tom Cruise',
      releaseDate: '2018',
      rating: 7,
      description: 'Ethan Hunt and his team race against time to recover stolen plutonium while being pursued by a CIA agent.',
    },
    {
      name: 'The Bourne Identity',
      length: '1h 59m',
      protagonist: 'Matt Damon',
      releaseDate: '2002',
      rating: 7,
      description: 'A man with amnesia discovers he has advanced combat skills and is pursued by assassins as he tries to uncover his identity.',
    },
    {
      name: 'Inception',
      length: '2h 28m',
      protagonist: 'Leonardo DiCaprio',
      releaseDate: '2010',
      rating: 8,
      description: 'A thief skilled in the art of extraction enters people\'s dreams to steal information and must now perform an inception.',
    },
    {
      name: 'The Matrix',
      length: '2h 16m',
      protagonist: 'Keanu Reeves',
      releaseDate: '1999',
      rating: 9,
      description: 'A computer hacker learns the truth about reality and becomes the chosen one to lead a rebellion against machines.',
    },
    {
      name: 'Lethal Weapon',
      length: '1h 50m',
      protagonist: 'Mel Gibson',
      releaseDate: '1987',
      rating: 7,
      description: 'A mismatched pair of LAPD detectives must put aside their differences to bring down a drug smuggling operation.',
    },
    {
      name: 'Taken',
      length: '1h 33m',
      protagonist: 'Liam Neeson',
      releaseDate: '2008',
      rating: 7,
      description: 'A retired CIA agent uses his skills to rescue his daughter who has been kidnapped by human traffickers in Paris.',
    },
    {
      name: 'The Raid',
      length: '1h 41m',
      protagonist: 'Iko Uwais',
      releaseDate: '2011',
      rating: 8,
      description: 'A rookie cop must fight his way through a dangerous tenement building to take down a ruthless crime lord.',
    },
    {
      name: 'Kill Bill: Volume 1',
      length: '1h 51m',
      protagonist: 'Uma Thurman',
      releaseDate: '2003',
      rating: 8,
      description: 'A former assassin seeks revenge on her former team members who betrayed her and left her for dead.',
    },
    {
      name: 'The Avengers',
      length: '2h 23m',
      protagonist: 'Robert Downey Jr.',
      releaseDate: '2012',
      rating: 8,
      description: 'A team of superheroes comes together to save the world from a powerful enemy threatening global destruction.',
    },
    {
      name: 'Gladiator',
      length: '2h 35m',
      protagonist: 'Russell Crowe',
      releaseDate: '2000',
      rating: 8,
      description: 'A former Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.',
    },
    {
      name: 'The Fast and the Furious',
      length: '1h 47m',
      protagonist: 'Vin Diesel',
      releaseDate: '2001',
      rating: 7,
      description: 'A skilled street racer teams up with an undercover cop to bring down a gang involved in high-stakes car theft.',
    },
    {
      name: 'Raiders of the Lost Ark',
      length: '1h 55m',
      protagonist: 'Harrison Ford',
      releaseDate: '1981',
      rating: 8,
      description: 'An archaeologist must prevent the Nazis from obtaining a powerful artifact that could change the fate of the world.',
    },
    {
      name: 'Edge of Tomorrow',
      length: '1h 53m',
      protagonist: 'Tom Cruise',
      releaseDate: '2014',
      rating: 8,
      description: 'A soldier caught in a time loop relives the same battle against alien invaders, gaining skills with each iteration.',
    },
    {
      name: 'Speed',
      length: '1h 56m',
      protagonist: 'Keanu Reeves',
      releaseDate: '1994',
      rating: 7,
      description: 'A cop must prevent a bomb on a bus from exploding by keeping its speed above 50 miles per hour.',
    },
    {
      name: 'The Terminator',
      length: '1h 47m',
      protagonist: 'Arnold Schwarzenegger',
      releaseDate: '1984',
      rating: 8,
      description: 'A cyborg assassin is sent back in time to kill a woman whose unborn son will lead humanity in a war against machines.',
    },
    {
      name: 'Predator',
      length: '1h 47m',
      protagonist: 'Arnold Schwarzenegger',
      releaseDate: '1987',
      rating: 8,
      description: 'A team of commandos on a rescue mission in a Central American jungle becomes the prey of an alien creature.',
    },
    {
      name: 'The Equalizer',
      length: '2h 12m',
      protagonist: 'Denzel Washington',
      releaseDate: '2014',
      rating: 7,
      description: 'A retired intelligence officer uses his skills to protect a young woman from Russian gangsters.',
    },
    // Add more action movies here
  ];
  
  module.exports = actionMovies;
  