const crimeMovies = [
    {
      name: 'The Godfather',
      length: '2h 58m',
      protagonist: 'Marlon Brando',
      releaseDate: '1972',
      rating: 9,
      description: 'The aging patriarch of a crime family transfers control of his empire to his reluctant son.',
    },
    {
      name: 'Pulp Fiction',
      length: '2h 34m',
      protagonist: 'John Travolta',
      releaseDate: '1994',
      rating: 8,
      description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    },
    {
      name: 'Goodfellas',
      length: '2h 26m',
      protagonist: 'Robert De Niro',
      releaseDate: '1990',
      rating: 9,
      description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
    },
    {
      name: 'The Departed',
      length: '2h 31m',
      protagonist: 'Leonardo DiCaprio',
      releaseDate: '2006',
      rating: 8,
      description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    },
    {
      name: 'Heat',
      length: '2h 50m',
      protagonist: 'Al Pacino',
      releaseDate: '1995',
      rating: 8,
      description: 'A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.',
    },
    {
      name: 'The Usual Suspects',
      length: '1h 46m',
      protagonist: 'Kevin Spacey',
      releaseDate: '1995',
      rating: 8,
      description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.',
    },
    {
      name: 'Scarface',
      length: '2h 50m',
      protagonist: 'Al Pacino',
      releaseDate: '1983',
      rating: 8,
      description: 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.',
    },
    {
      name: 'Reservoir Dogs',
      length: '1h 39m',
      protagonist: 'Harvey Keitel',
      releaseDate: '1992',
      rating: 8,
      description: 'After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.',
    },
    {
      name: 'The Shawshank Redemption',
      length: '2h 22m',
      protagonist: 'Tim Robbins',
      releaseDate: '1994',
      rating: 9,
      description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    },
    {
      name: 'No Country for Old Men',
      length: '2h 2m',
      protagonist: 'Josh Brolin',
      releaseDate: '2007',
      rating: 8,
      description: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.',
    },
    {
      name: 'The French Connection',
      length: '1h 44m',
      protagonist: 'Gene Hackman',
      releaseDate: '1971',
      rating: 7,
      description: 'A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection.',
    },
    {
      name: 'A Clockwork Orange',
      length: '2h 16m',
      protagonist: 'Malcolm McDowell',
      releaseDate: '1971',
      rating: 8,
      description: 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn\'t go as planned.',
    },
    {
      name: 'Chinatown',
      length: '2h 10m',
      protagonist: 'Jack Nicholson',
      releaseDate: '1974',
      rating: 8,
      description: 'A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.',
    },
    {
      name: 'L.A. Confidential',
      length: '2h 18m',
      protagonist: 'Kevin Spacey',
      releaseDate: '1997',
      rating: 8,
      description: 'As corruption grows in 1950s LA, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.',
    },
    {
      name: 'Training Day',
      length: '2h 2m',
      protagonist: 'Denzel Washington',
      releaseDate: '2001',
      rating: 7,
      description: 'On his first day on the job as a narcotics officer, a rookie cop goes on a 24-hour training course with a rogue detective who isn\'t what he appears.',
    },
    {
      name: 'The Town',
      length: '2h 5m',
      protagonist: 'Ben Affleck',
      releaseDate: '2010',
      rating: 7,
      description: 'As he plans his next job, a longtime thief tries to balance his feelings for a bank manager connected to one of his earlier heists, as well as the FBI agent looking to bring him and his crew down.',
    },
    {
      name: 'American Gangster',
      length: '2h 37m',
      protagonist: 'Denzel Washington',
      releaseDate: '2007',
      rating: 7,
      description: 'In 1970s America, a detective works to bring down the drug empire of Frank Lucas, a heroin kingpin from Manhattan, who is smuggling the drug into the country from the Far East.',
    },
    {
      name: 'Catch Me If You Can',
      length: '2h 21m',
      protagonist: 'Leonardo DiCaprio',
      releaseDate: '2002',
      rating: 8,
      description: 'The story of Frank Abagnale Jr., who before his 19th birthday successfully forged millions of dollars\' worth of checks while posing as a Pan Am pilot, a doctor, and a legal prosecutor.',
    },
    {
      name: 'The Departed',
      length: '2h 31m',
      protagonist: 'Leonardo DiCaprio',
      releaseDate: '2006',
      rating: 8,
      description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    },
    {
      name: 'Gone Girl',
      length: '2h 29m',
      protagonist: 'Ben Affleck',
      releaseDate: '2014',
      rating: 8,
      description: 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
    },
    {
      name: 'Memento',
      length: '1h 53m',
      protagonist: 'Guy Pearce',
      releaseDate: '2000',
      rating: 8,
      description: 'A man with short-term memory loss attempts to track down his wife\'s murderer.',
    },
    {
      name: 'Reservoir Dogs',
      length: '1h 39m',
      protagonist: 'Harvey Keitel',
      releaseDate: '1992',
      rating: 8,
      description: 'After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.',
    },
    {
      name: 'The Silence of the Lambs',
      length: '1h 58m',
      protagonist: 'Jodie Foster',
      releaseDate: '1991',
      rating: 8,
      description: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    },
    {
      name: 'Drive',
      length: '1h 40m',
      protagonist: 'Ryan Gosling',
      releaseDate: '2011',
      rating: 7,
      description: 'A mysterious Hollywood stuntman and mechanic moonlights as a getaway driver and finds himself in trouble when he helps out his neighbor.',
    },
    {
      name: 'The Big Lebowski',
      length: '1h 59m',
      protagonist: 'Jeff Bridges',
      releaseDate: '1998',
      rating: 8,
      description: 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.',
    },
    {
      name: 'The Girl with the Dragon Tattoo',
      length: '2h 38m',
      protagonist: 'Rooney Mara',
      releaseDate: '2011',
      rating: 7,
      description: 'Journalist Mikael Blomkvist is aided in his search for a woman who has been missing for forty years by Lisbeth Salander, a young computer hacker.',
    },
  ];
  
  module.exports = crimeMovies;
  