const dramaMovies = [
    {
      name: 'The Shawshank Redemption',
      length: '2h 22m',
      protagonist: 'Tim Robbins',
      releaseDate: '1994',
      rating: 9,
      description: 'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.',
    },
    {
      name: 'Forrest Gump',
      length: '2h 22m',
      protagonist: 'Tom Hanks',
      releaseDate: '1994',
      rating: 8,
      description: 'A simple man with a low IQ witnesses and unwittingly influences several defining historical events in the 20th century USA.',
    },
    {
      name: 'The Pursuit of Happyness',
      length: '1h 57m',
      protagonist: 'Will Smith',
      releaseDate: '2006',
      rating: 8,
      description: 'A struggling salesman takes custody of his son as he\'s poised to begin a life- changing professional endeavor.',
    },
    {
      name: 'Schindler\'s List',
      length: '3h 15m',
      protagonist: 'Liam Neeson',
      releaseDate: '1993',
      rating: 8,
      description: 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    },
    {
      name: 'Good Will Hunting',
      length: '2h 6m',
      protagonist: 'Matt Damon',
      releaseDate: '1997',
      rating: 8,
      description: 'Will Hunting, a janitor at MIT, has a gift for mathematics but needs help from a psychologist to find direction in his life.',
    },
    {
      name: 'The Green Mile',
      length: '3h 9m',
      protagonist: 'Tom Hanks',
      releaseDate: '1999',
      rating: 8,
      description: 'The lives of guards on Death Row are affected by a new inmate, John Coffey, who has a mysterious gift.',
    },
    {
      name: 'The Notebook',
      length: '2h 3m',
      protagonist: 'Ryan Gosling',
      releaseDate: '2004',
      rating: 7,
      description: 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated due to their social differences.',
    },
    {
      name: 'A Beautiful Mind',
      length: '2h 16m',
      protagonist: 'Russell Crowe',
      releaseDate: '2001',
      rating: 8,
      description: 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.',
    },
    {
      name: 'The Fault in Our Stars',
      length: '2h 6m',
      protagonist: 'Shailene Woodley',
      releaseDate: '2014',
      rating: 7,
      description: 'Two teenagers meet at a cancer support group and fall in love, despite the terminal diagnosis they both share.',
    },
    {
      name: 'The Lion King',
      length: '1h 28m',
      protagonist: 'Matthew Broderick',
      releaseDate: '1994',
      rating: 8,
      description: 'A young lion prince flees his kingdom after the murder of his father, while learning the true meaning of responsibility and bravery.',
    },
    {
      name: 'Dead Poets Society',
      length: '2h 8m',
      protagonist: 'Robin Williams',
      releaseDate: '1989',
      rating: 8,
      description: 'English teacher John Keating inspires his students to look at poetry with a different perspective of authentic knowledge and feelings.',
    },
    {
      name: 'Eternal Sunshine of the Spotless Mind',
      length: '1h 48m',
      protagonist: 'Jim Carrey',
      releaseDate: '2004',
      rating: 8,
      description: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
    },
    {
      name: 'The Great Gatsby',
      length: '2h 23m',
      protagonist: 'Leonardo DiCaprio',
      releaseDate: '2013',
      rating: 7,
      description: 'A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.',
    },
    {
      name: 'Whiplash',
      length: '1h 47m',
      protagonist: 'Miles Teller',
      releaseDate: '2014',
      rating: 8,
      description: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
    },
    {
      name: 'Rain Man',
      length: '2h 13m',
      protagonist: 'Dustin Hoffman',
      releaseDate: '1988',
      rating: 8,
      description: 'Selfish yuppie Charlie Babbitt\'s father left a fortune to his savant brother Raymond and a pittance to Charlie; they travel cross-country.',
    },
    {
      name: 'Million Dollar Baby',
      length: '2h 12m',
      protagonist: 'Clint Eastwood',
      releaseDate: '2004',
      rating: 8,
      description: 'A determined woman works with a hardened boxing trainer to become a professional.',
    },
    {
      name: 'Life Is Beautiful',
      length: '1h 56m',
      protagonist: 'Roberto Benigni',
      releaseDate: '1997',
      rating: 8,
      description: 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.',
    },
    {
      name: 'American Beauty',
      length: '2h 2m',
      protagonist: 'Kevin Spacey',
      releaseDate: '1999',
      rating: 8,
      description: 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter\'s best friend.',
    },
    {
      name: 'The Help',
      length: '2h 26m',
      protagonist: 'Emma Stone',
      releaseDate: '2011',
      rating: 8,
      description: 'An aspiring author during the civil rights movement of the 1960s decides to write a book detailing the African American maids\' point of view on the white families for which they work, and the hardships they go through on a daily basis.',
    },
    {
      name: 'Gone with the Wind',
      length: '3h 58m',
      protagonist: 'Vivien Leigh',
      releaseDate: '1939',
      rating: 8,
      description: 'A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods.',
    },
  ];
  
  module.exports = dramaMovies;
  