const romanceMovies = [
    {
      name: 'The Notebook',
      length: '2h 3m',
      releaseDate: 'June 25, 2004',
      rating: 4.3,
      director: 'Nick Cassavetes',
      genre: 'Romance, Drama',
      protagonist: 'Noah Calhoun',
      description: 'A classic love story about a young couple who are separated by war and class differences, only to reunite years later.',
    },
    {
      name: 'La La Land',
      length: '2h 8m',
      releaseDate: 'December 9, 2016',
      rating: 4.5,
      director: 'Damien Chazelle',
      genre: 'Romance, Musical',
      protagonist: 'Mia Dolan, Sebastian Wilder',
      description: 'A modern musical about an aspiring actress and a jazz musician who fall in love while pursuing their dreams in Los Angeles.',
    },
    {
      name: '500 Days of Summer',
      length: '1h 35m',
      releaseDate: 'July 17, 2009',
      rating: 4.2,
      director: 'Marc Webb',
      genre: 'Romance, Drama',
      protagonist: 'Tom Hansen, Summer Finn',
      description: 'A nonlinear story of a man reflecting on his failed relationship with a woman named Summer.',
    },
    {
      name: 'Pride and Prejudice',
      length: '2h 9m',
      releaseDate: 'November 23, 2005',
      rating: 4.4,
      director: 'Joe Wright',
      genre: 'Romance, Drama',
      protagonist: 'Elizabeth Bennet, Mr. Darcy',
      description: 'A classic adaptation of Jane Austen\'s novel about the complex relationship between Elizabeth Bennet and Mr. Darcy.',
    },
    {
      name: 'Before Sunrise',
      length: '1h 41m',
      releaseDate: 'January 27, 1995',
      rating: 4.2,
      director: 'Richard Linklater',
      genre: 'Romance, Drama',
      protagonist: 'Jesse, Celine',
      description: 'Two strangers meet on a train and spend a night together in Vienna, knowing they may never see each other again.',
    },
    {
      name: 'The Fault in Our Stars',
      length: '2h 6m',
      releaseDate: 'June 6, 2014',
      rating: 4.3,
      director: 'Josh Boone',
      genre: 'Romance, Drama',
      protagonist: 'Hazel Grace Lancaster, Augustus Waters',
      description: 'A heart-wrenching story of two teenagers who meet and fall in love at a cancer support group.',
    },
    {
      name: 'Eternal Sunshine of the Spotless Mind',
      length: '1h 48m',
      releaseDate: 'March 19, 2004',
      rating: 4.4,
      director: 'Michel Gondry',
      genre: 'Romance, Drama, Sci-Fi',
      protagonist: 'Joel Barish, Clementine Kruczynski',
      description: 'After a painful breakup, a man undergoes a medical procedure to erase memories of his former girlfriend, but the process makes him realize he wants to keep them.',
    },
    {
      name: 'A Walk to Remember',
      length: '1h 41m',
      releaseDate: 'January 25, 2002',
      rating: 4.3,
      director: 'Adam Shankman',
      genre: 'Romance, Drama',
      protagonist: 'Landon Carter, Jamie Sullivan',
      description: 'A high school bad boy falls in love with a sweet and religious girl who has a secret of her own.',
    },
    {
      name: 'Casablanca',
      length: '1h 42m',
      releaseDate: 'January 23, 1943',
      rating: 4.5,
      director: 'Michael Curtiz',
      genre: 'Romance, Drama',
      protagonist: 'Rick Blaine, Ilsa Lund',
      description: 'Set during World War II, a nightclub owner must choose between his love for a woman and helping her and her husband escape from the Nazis.',
    },
    {
      name: 'Romeo + Juliet',
      length: '2h',
      releaseDate: 'November 1, 1996',
      rating: 4.3,
      director: 'Baz Luhrmann',
      genre: 'Romance, Drama',
      protagonist: 'Romeo Montague, Juliet Capulet',
      description: 'A modern adaptation of Shakespeare\'s play, telling the tragic love story of two young lovers from feuding families.',
    },
    {
      name: 'The Princess Bride',
      length: '1h 38m',
      releaseDate: 'October 9, 1987',
      rating: 4.5,
      director: 'Rob Reiner',
      genre: 'Adventure, Family, Fantasy, Romance',
      protagonist: 'Westley, Buttercup',
      description: 'A fairy-tale adventure about a young woman named Buttercup and her true love, Westley, as they embark on a quest to rescue her from an unwanted marriage.',
    },
    {
      name: 'Titanic',
      length: '3h 30m',
      releaseDate: 'December 19, 1997',
      rating: 4.5,
      director: 'James Cameron',
      genre: 'Romance, Drama',
      protagonist: 'Jack Dawson, Rose DeWitt Bukater',
      description: 'A tragic love story between a poor artist and a wealthy woman aboard the ill-fated Titanic.',
    },
    {
      name: 'Love, Simon',
      length: '1h 50m',
      releaseDate: 'March 16, 2018',
      rating: 4.2,
      director: 'Greg Berlanti',
      genre: 'Romance, Drama, Comedy',
      protagonist: 'Simon Spier',
      description: 'A heartwarming coming-of-age story about a high school boy who is on a journey to discover his true self and find love along the way.',
    },
    {
      name: 'Dear John',
      length: '1h 48m',
      releaseDate: 'February 5, 2010',
      rating: 4.2,
      director: 'Lasse Hallström',
      genre: 'Romance, Drama, War',
      protagonist: 'John Tyree, Savannah Curtis',
      description: 'A soldier falls in love with a college student, but their relationship is tested when he is deployed to serve in the military.',
    },
    {
      name: 'About Time',
      length: '2h 3m',
      releaseDate: 'August 8, 2013',
      rating: 4.4,
      director: 'Richard Curtis',
      genre: 'Romance, Drama, Fantasy',
      protagonist: 'Tim Lake',
      description: 'A young man discovers that he can time travel and decides to use this ability to find love and create meaningful moments in his life.',
    },
    {
      name: 'The Fault in Our Stars',
      length: '2h 6m',
      releaseDate: 'June 6, 2014',
      rating: 4.3,
      director: 'Josh Boone',
      genre: 'Romance, Drama',
      protagonist: 'Hazel Grace Lancaster, Augustus Waters',
      description: 'A heart-wrenching story of two teenagers who meet and fall in love at a cancer support group.',
    },
    {
      name: 'Pretty Woman',
      length: '1h 59m',
      releaseDate: 'March 23, 1990',
      rating: 4.4,
      director: 'Garry Marshall',
      genre: 'Romance, Comedy',
      protagonist: 'Edward Lewis, Vivian Ward',
      description: 'A wealthy businessman falls in love with a prostitute whom he hires to accompany him to social events.',
    },
    {
      name: 'The Vow',
      length: '1h 44m',
      releaseDate: 'February 10, 2012',
      rating: 4.3,
      director: 'Michael Sucsy',
      genre: 'Romance, Drama',
      protagonist: 'Paige Collins, Leo Collins',
      description: 'A woman loses her memory in a car accident and her husband must work to win her heart again.',
    },
    {
      name: 'A Star Is Born',
      length: '2h 16m',
      releaseDate: 'October 5, 2018',
      rating: 4.4,
      director: 'Bradley Cooper',
      genre: 'Romance, Drama, Music',
      protagonist: 'Jackson Maine, Ally Maine',
      description: 'A famous musician helps a young singer find fame, but their relationship is tested by the music industry and personal demons.',
    },
    {
      name: 'The Time Traveler\'s Wife',
      length: '1h 47m',
      releaseDate: 'August 14, 2009',
      rating: 4.3,
      director: 'Robert Schwentke',
      genre: 'Romance, Drama, Fantasy',
      protagonist: 'Henry DeTamble, Clare Abshire',
      description: 'A librarian with a genetic disorder involuntarily time travels, which causes complications in his relationship with his wife.',
    },
    {
      name: 'Crazy Rich Asians',
      length: '2h 1m',
      releaseDate: 'August 15, 2018',
      rating: 4.2,
      director: 'Jon M. Chu',
      genre: 'Romance, Comedy, Drama',
      protagonist: 'Rachel Chu, Nick Young',
      description: 'A woman travels to Singapore to meet her boyfriend\'s wealthy family and faces unexpected challenges.',
    },
    {
      name: 'Me Before You',
      length: '1h 50m',
      releaseDate: 'June 3, 2016',
      rating: 4.3,
      director: 'Thea Sharrock',
      genre: 'Romance, Drama',
      protagonist: 'Louisa Clark, Will Traynor',
      description: 'A young woman becomes the caregiver for a wealthy man who is paralyzed from an accident, and they form an unlikely bond.',
    },
  ];
  
  module.exports = romanceMovies;
  