const top250Movies = [
    {
      rank: 1,
      name: 'The Shawshank Redemption',
      releaseDate: '1994',
      length: '2h 22m',
      rating: 9.3,
      director: 'Frank Darabont',
      genre: 'Drama',
      description: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
    },
    {
      rank: 2,
      name: 'The Godfather',
      releaseDate: '1972',
      length: '2h 55m',
      rating: 9.2,
      director: 'Francis Ford Coppola',
      genre: 'Crime',
      description: 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.',
    },
    {
      rank: 3,
      name: 'The Dark Knight',
      releaseDate: '2008',
      length: '2h 32m',
      rating: 9.0,
      director: 'Christopher Nolan',
      genre: 'Action',
      description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    },
    {
      rank: 4,
      name: 'The Godfather Part II',
      releaseDate: '1974',
      length: '3h 22m',
      rating: 9.0,
      director: 'Francis Ford Coppola',
      genre: 'Crime',
      description: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    },
    {
      rank: 5,
      name: '12 Angry Men',
      releaseDate: '1957',
      length: '1h 36m',
      rating: 9.0,
      director: 'Sidney Lumet',
      genre: 'Drama',
      description: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    },
    {
      rank: 6,
      name: "Schindler's List",
      releaseDate: '1993',
      length: '3h 15m',
      rating: 9.0,
      director: 'Steven Spielberg',
      genre: 'Drama',
      description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    },
    {
      rank: 7,
      name: 'The Lord of the Rings: The Return of the King',
      releaseDate: '2003',
      length: '3h 21m',
      rating: 9.0,
      director: 'Peter Jackson',
      genre: 'Adventure',
      description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    },
    {
      rank: 8,
      name: 'Pulp Fiction',
      releaseDate: '1994',
      length: '2h 34m',
      rating: 8.9,
      director: 'Quentin Tarantino',
      genre: 'Crime',
      description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    },
    {
      rank: 9,
      name: 'The Lord of the Rings: The Fellowship of the Ring',
      releaseDate: '2001',
      length: '2h 58m',
      rating: 8.8,
      director: 'Peter Jackson',
      genre: 'Adventure',
      description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    },
    {
      rank: 10,
      name: 'The Good, the Bad and the Ugly',
      releaseDate: '1966',
      length: '2h 58m',
      rating: 8.8,
      director: 'Sergio Leone',
      genre: 'Western',
      description: 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    },
    {
      rank: 11,
      name: "Forrest Gump",
      releaseDate: 1994,
      length: "2h 22m",
      rating: 8.8,
      director: "Robert Zemeckis",
      genre: "Drama, Romance",
      description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    },
    {
      rank: 12,
      name: "Spider-Man: Across the Spider-Verse",
      releaseDate: 2023,
      length: "2h 20m",
      rating: 8.9,
      director: "Joaquim Dos Santos",
      genre: "Animation, Action, Adventure",
      description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
    },
    {
      rank: 13,
      name: "Fight Club",
      releaseDate: 1999,
      length: "2h 19m",
      rating: 8.8,
      director: "David Fincher",
      genre: "Drama",
      description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    },
    {
      rank: 14,
      name: "The Lord of the Rings: The Two Towers",
      releaseDate: 2002,
      length: "2h 59m",
      rating: 8.8,
      director: "Peter Jackson",
      genre: "Adventure, Drama, Fantasy",
      description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    },
    {
      rank: 15,
      name: "Inception",
      releaseDate: 2010,
      length: "2h 28m",
      rating: 8.8,
      director: "Christopher Nolan",
      genre: "Action, Adventure, Sci-Fi",
      description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    },
    {
      rank: 16,
      name: "Star Wars: Episode V - The Empire Strikes Back",
      releaseDate: 1980,
      length: "2h 4m",
      rating: 8.7,
      director: "Irvin Kershner",
      genre: "Action, Adventure, Fantasy",
      description: "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
    },
    {
      rank: 17,
      name: "The Matrix",
      releaseDate: 1999,
      length: "2h 16m",
      rating: 8.7,
      director: "Lana Wachowski",
      genre: "Action, Sci-Fi",
      description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    },
    {
      rank: 18,
      name: "GoodFellas",
      releaseDate: 1990,
      length: "2h 25m",
      rating: 8.7,
      director: "Martin Scorsese",
      genre: "Biography, Crime, Drama",
      description: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
    },
    {
      rank: 19,
      name: "One Flew Over the Cuckoo's Nest",
      releaseDate: 1975,
      length: "2h 13m",
      rating: 8.7,
      director: "Milos Forman",
      genre: "Drama",
      description: "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.",
    },
    {
      rank: 20,
      name: "Seven",
      releaseDate: 1995,
      length: "2h 7m",
      rating: 8.6,
      director: "David Fincher",
      genre: "Crime, Drama, Mystery",
      description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    },
    {
      rank: 21,
      name: "It's a Wonderful Life",
      releaseDate: 1946,
      length: "2h 10m",
      rating: 8.6,
      director: "Frank Capra",
      genre: "Drama, Family, Fantasy",
      description: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
    },
    {
      rank: 22,
      name: "Seven Samurai",
      releaseDate: 1954,
      length: "3h 27m",
      rating: 8.6,
      director: "Akira Kurosawa",
      genre: "Action, Adventure, Drama",
      description: "Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.",
    },
    {
      rank: 23,
      name: "The Silence of the Lambs",
      releaseDate: 1991,
      length: "1h 58m",
      rating: 8.6,
      director: "Jonathan Demme",
      genre: "Crime, Drama, Thriller",
      description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    },
    {
      rank: 24,
      name: "Saving Private Ryan",
      releaseDate: 1998,
      length: "2h 49m",
      rating: 8.6,
      director: "Steven Spielberg",
      genre: "Drama, War",
      description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    },
    {
      rank: 25,
      name: "City of God",
      releaseDate: 2002,
      length: "2h 10m",
      rating: 8.6,
      director: "Fernando Meirelles",
      genre: "Crime, Drama",
      description: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    },
    {
      rank: 26,
      name: "Interstellar",
      releaseDate: 2014,
      length: "2h 49m",
      rating: 8.7,
      director: "Christopher Nolan",
      genre: "Adventure, Drama, Sci-Fi",
      description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    },
    {
      rank: 27,
      name: "Life Is Beautiful",
      releaseDate: 1997,
      length: "1h 56m",
      rating: 8.6,
      director: "Roberto Benigni",
      genre: "Comedy, Drama, Romance",
      description: "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.",
    },
    {
      rank: 28,
      name: "The Green Mile",
      releaseDate: 1999,
      length: "3h 9m",
      rating: 8.6,
      director: "Frank Darabont",
      genre: "Crime, Drama, Fantasy",
      description: "A tale set on death row in a Southern jail, where gentle giant John possesses the mysterious power to heal people's ailments. When the lead guard, Paul, recognizes John's gift, he tries to help stave off the condemned man's execution.",
    },
    {
      rank: 29,
      name: "Star Wars: Episode IV - A New Hope",
      releaseDate: 1977,
      length: "2h 1m",
      rating: 8.6,
      director: "George Lucas",
      genre: "Action, Adventure, Fantasy",
      description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
    },
    {
      rank: 30,
      name: "Terminator 2: Judgment Day",
      releaseDate: 1991,
      length: "2h 17m",
      rating: 8.6,
      director: "James Cameron",
      genre: "Action, Sci-Fi",
      description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.",
    },
    {
      rank: 31,
      name: "Back to the Future",
      releaseDate: 1985,
      length: "1h 56m",
      rating: 8.5,
      director: "Robert Zemeckis",
      genre: "Adventure, Comedy, Sci-Fi",
      description: "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
    },
    {
      rank: 32,
      name: "Spirited Away",
      releaseDate: 2001,
      length: "2h 5m",
      rating: 8.6,
      director: "Hayao Miyazaki",
      genre: "Animation, Adventure, Family",
      description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.",
    },
    {
      rank: 33,
      name: "The Pianist",
      releaseDate: 2002,
      length: "2h 30m",
      rating: 8.5,
      director: "Roman Polanski",
      genre: "Biography, Drama, Music",
      description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    },
    {
      rank: 34,
      name: "Psycho",
      releaseDate: 1960,
      length: "1h 49m",
      rating: 8.5,
      director: "Alfred Hitchcock",
      genre: "Horror, Mystery, Thriller",
      description: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.",
    },
    {
      rank: 35,
      name: "Parasite",
      releaseDate: 2019,
      length: "2h 12m",
      rating: 8.5,
      director: "Bong Joon Ho",
      genre: "Comedy, Drama, Thriller",
      description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    },
    {
      rank: 36,
      name: "Leon",
      releaseDate: 1994,
      length: "1h 50m",
      rating: 8.5,
      director: "Luc Besson",
      genre: "Action, Crime, Drama",
      description: "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
    },
    {
      rank: 37,
      name: "The Lion King",
      releaseDate: 1994,
      length: "1h 28m",
      rating: 8.5,
      director: "Roger Allers, Rob Minkoff",
      genre: "Animation, Adventure, Drama",
      description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    },
    {
      rank: 38,
      name: "Gladiator",
      releaseDate: 2000,
      length: "2h 35m",
      rating: 8.5,
      director: "Ridley Scott",
      genre: "Action, Adventure, Drama",
      description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    },
    {
      rank: 39,
      name: "American History X",
      releaseDate: 1998,
      length: "1h 59m",
      rating: 8.5,
      director: "Tony Kaye",
      genre: "Crime, Drama",
      description: "Living a life marked by violence, neo-Nazi Derek finally goes to prison after killing two black youths. Upon his release, Derek vows to change; he hopes to prevent his brother, Danny, who idolizes Derek, from following in his footsteps.",
    },
    {
      rank: 40,
      name: "The Departed",
      releaseDate: 2006,
      length: "2h 31m",
      rating: 8.5,
      director: "Martin Scorsese",
      genre: "Crime, Drama, Thriller",
      description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    },
    {
      rank: 41,
      name: "Whiplash",
      releaseDate: 2014,
      length: "1h 46m",
      rating: 8.5,
      director: "Damien Chazelle",
      genre: "Drama, Music",
      description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    },
    {
      rank: 42,
      name: "The Prestige",
      releaseDate: 2006,
      length: "2h 10m",
      rating: 8.5,
      director: "Christopher Nolan",
      genre: "Drama, Mystery, Sci-Fi",
      description: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    },
    {
      rank: 43,
      name: "The Usual Suspects",
      releaseDate: 1995,
      length: "1h 46m",
      rating: 8.5,
      director: "Bryan Singer",
      genre: "Crime, Mystery, Thriller",
      description: "The sole survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup.",
    },
    {
      rank: 44,
      name: "Casablanca",
      releaseDate: 1942,
      length: "1h 42m",
      rating: 8.5,
      director: "Michael Curtiz",
      genre: "Drama, Romance, War",
      description: "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.",
    },
    {
      rank: 45,
      name: "Grave of the Fireflies",
      releaseDate: 1988,
      length: "1h 29m",
      rating: 8.5,
      director: "Isao Takahata",
      genre: "Animation, Drama, War",
      description: "A young boy and his little sister struggle to survive in Japan during World War II.",
    },
    {
      rank: 46,
      name: "Harakiri",
      releaseDate: 1962,
      length: "2h 13m",
      rating: 8.6,
      director: "Masaki Kobayashi",
      genre: "Action, Drama, Mystery",
      description: "When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.",
    },
    {
      rank: 47,
      name: "Untouchable",
      releaseDate: 2011,
      length: "1h 52m",
      rating: 8.5,
      director: "Olivier Nakache, Éric Toledano",
      genre: "Biography, Comedy, Drama",
      description: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
    },
    {
      rank: 48,
      name: "Modern Times",
      releaseDate: 1936,
      length: "1h 27m",
      rating: 8.5,
      director: "Charles Chaplin",
      genre: "Comedy, Drama, Family",
      description: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
    },
    {
      rank: 49,
      name: "Once Upon a Time in the West",
      releaseDate: 1968,
      length: "2h 45m",
      rating: 8.5,
      director: "Sergio Leone",
      genre: "Western",
      description: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
    },
    {
      rank: 50,
      name: "Cinema Paradiso",
      releaseDate: 1988,
      length: "2h 35m",
      rating: 8.5,
      director: "Giuseppe Tornatore",
      genre: "Drama",
      description: "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema's projectionist.",
    },
    {
      rank: 51,
      name: "Rear Window",
      releaseDate: 1954,
      length: "1h 52m",
      rating: 8.5,
      director: "Alfred Hitchcock",
      genre: "Mystery, Thriller",
      description: "A photographer in a wheelchair spies on his neighbors from his Greenwich Village courtyard apartment window, and becomes convinced one of them has committed murder, despite the skepticism of his fashion-model girlfriend.",
    },
    {
      rank: 52,
      name: "Alien",
      releaseDate: 1979,
      length: "1h 57m",
      rating: 8.5,
      director: "Ridley Scott",
      genre: "Horror, Sci-Fi",
      description: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
    },
    {
      rank: 53,
      name: "City Lights",
      releaseDate: 1931,
      length: "1h 27m",
      rating: 8.5,
      director: "Charles Chaplin",
      genre: "Comedy, Drama, Romance",
      description: "With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.",
    },
    {
      rank: 54,
      name: "Apocalypse Now",
      releaseDate: 1979,
      length: "2h 27m",
      rating: 8.4,
      director: "Francis Ford Coppola",
      genre: "Drama, Mystery, War",
      description: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
    },
    {
      rank: 55,
      name: "Memento",
      releaseDate: 2000,
      length: "1h 53m",
      rating: 8.4,
      director: "Christopher Nolan",
      genre: "Mystery, Thriller",
      description: "A man with short-term memory loss attempts to track down his wife's murderer.",
    },
    {
      rank: 56,
      name: "Django Unchained",
      releaseDate: 2012,
      length: "2h 45m",
      rating: 8.4,
      director: "Quentin Tarantino",
      genre: "Drama, Western",
      description: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
    },
    {
      rank: 57,
      name: "Raiders of the Lost Ark",
      releaseDate: 1981,
      length: "1h 55m",
      rating: 8.4,
      director: "Steven Spielberg",
      genre: "Action, Adventure",
      description: "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis can obtain its awesome powers.",
    },
    {
      rank: 58,
      name: "WALL·E",
      releaseDate: 2008,
      length: "1h 38m",
      rating: 8.4,
      director: "Andrew Stanton",
      genre: "Animation, Adventure, Family",
      description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    },
    {
      rank: 59,
      name: "The Lives of Others",
      releaseDate: 2006,
      length: "2h 17m",
      rating: 8.4,
      director: "Florian Henckel von Donnersmarck",
      genre: "Drama, Thriller",
      description: "In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.",
    },
    {
      rank: 60,
      name: "Sunset Blvd.",
      releaseDate: 1950,
      length: "1h 50m",
      rating: 8.4,
      director: "Billy Wilder",
      genre: "Drama, Film-Noir",
      description: "A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.",
    },
    {
      rank: 61,
      name: "Paths of Glory",
      releaseDate: 1957,
      length: "1h 28m",
      rating: 8.4,
      director: "Stanley Kubrick",
      genre: "Drama, War",
      description:
        "After refusing to attack an enemy position, a general accuses the soldiers of cowardice, and their commanding officer must defend them.",
    },
    {
      rank: 62,
      name: "Avengers: Infinity War",
      releaseDate: 2018,
      length: "2h 29m",
      rating: 8.4,
      director: "Anthony Russo",
      genre: "Action, Adventure, Sci-Fi",
      description:
        "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    },
    {
      rank: 63,
      name: "The Shining",
      releaseDate: 1980,
      length: "2h 26m",
      rating: 8.4,
      director: "Stanley Kubrick",
      genre: "Drama, Horror",
      description:
        "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
    },
    {
      rank: 64,
      name: "The Great Dictator",
      releaseDate: 1940,
      length: "2h 5m",
      rating: 8.4,
      director: "Charles Chaplin",
      genre: "Comedy, Drama, War",
      description:
        "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
    },
    {
      rank: 65,
      name: "Witness for the Prosecution",
      releaseDate: 1957,
      length: "1h 56m",
      rating: 8.4,
      director: "Billy Wilder",
      genre: "Crime, Drama, Mystery",
      description:
        "A veteran British barrister must defend his client in a murder trial that has surprise after surprise.",
    },
    {
      rank: 66,
      name: "Spider-Man: Into the Spider-Verse",
      releaseDate: 2018,
      length: "1h 57m",
      rating: 8.4,
      director: "Bob Persichetti",
      genre: "Animation, Action, Adventure",
      description:
        "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    },
    {
      rank: 67,
      name: "Aliens",
      releaseDate: 1986,
      length: "2h 17m",
      rating: 8.4,
      director: "James Cameron",
      genre: "Action, Adventure, Sci-Fi",
      description:
        "Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.",
    },
    {
      rank: 68,
      name: "American Beauty",
      releaseDate: 1999,
      length: "2h 2m",
      rating: 8.3,
      director: "Sam Mendes",
      genre: "Drama, Romance",
      description:
        "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
    },
    {
      rank: 69,
      name: "The Dark Knight Rises",
      releaseDate: 2012,
      length: "2h 44m",
      rating: 8.4,
      director: "Christopher Nolan",
      genre: "Action, Adventure",
      description:
        "Eight years after the Joker's reign of chaos, Batman is coerced out of exile with the assistance of the mysterious Selina Kyle in order to defend Gotham City from the vicious guerrilla terrorist Bane.",
    },
    {
      rank: 70,
      name: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
      releaseDate: 1964,
      length: "1h 35m",
      rating: 8.4,
      director: "Stanley Kubrick",
      genre: "Comedy",
      description:
        "An insane American general orders a bombing attack on the Soviet Union, triggering a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.",
    },
    {
      rank: 71,
      name: "Inglourious Basterds",
      releaseDate: 2009,
      length: "2h 33m",
      rating: 8.3,
      director: "Quentin Tarantino",
      genre: "Adventure, Drama, War",
      description:
        "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
    },
    {
      rank: 72,
      name: "Oldboy",
      releaseDate: 2003,
      length: "2h",
      rating: 8.4,
      director: "Park Chan-wook",
      genre: "Action, Drama, Mystery",
      description:
        "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
    },
    {
      rank: 73,
      name: "Coco",
      releaseDate: 2017,
      length: "1h 45m",
      rating: 8.4,
      director: "Lee Unkrich",
      genre: "Animation, Adventure, Family",
      description:
        "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    },
    {
      rank: 74,
      name: "Amadeus",
      releaseDate: 1984,
      length: "2h 40m",
      rating: 8.4,
      director: "Milos Forman",
      genre: "Biography, Drama, History",
      description:
        "The life, success, and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was deeply jealous of Mozart's talent and claimed to have murdered him.",
    },
    {
      rank: 75,
      name: "Toy Story",
      releaseDate: 1995,
      length: "1h 21m",
      rating: 8.3,
      director: "John Lasseter",
      genre: "Animation, Adventure, Comedy",
      description:
        "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as the top toy in a boy's bedroom.",
    },
    {
      rank: 76,
      name: "Braveheart",
      releaseDate: 1995,
      length: "2h 58m",
      rating: 8.3,
      director: "Mel Gibson",
      genre: "Biography, Drama, History",
      description:
        "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
    },
    {
      rank: 77,
      name: "Das Boot",
      releaseDate: 1981,
      length: "2h 29m",
      rating: 8.4,
      director: "Wolfgang Petersen",
      genre: "Adventure, Drama, Thriller",
      description:
        "A German U-boat stalks the frigid waters of the North Atlantic as its young crew experiences the sheer terror and claustrophobic life of a submariner in World War II.",
    },
    {
      rank: 78,
      name: "Joker",
      releaseDate: 2019,
      length: "2h 2m",
      rating: 8.4,
      director: "Todd Phillips",
      genre: "Crime, Drama, Thriller",
      description:
        "The rise of Arthur Fleck, from aspiring stand-up comedian and pariah to Gotham's clown prince and leader of the revolution.",
    },
    {
      rank: 79,
      name: "Avengers: Endgame",
      releaseDate: 2019,
      length: "3h 1m",
      rating: 8.4,
      director: "Anthony Russo",
      genre: "Action, Adventure, Drama",
      description:
        "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    },
    {
      rank: 80,
      name: "Princess Mononoke",
      releaseDate: 1997,
      length: "2h 14m",
      rating: 8.3,
      director: "Hayao Miyazaki",
      genre: "Animation, Adventure, Fantasy",
      description:
        "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest, he also meets San, the Mononoke Hime.",
    },
    {
      rank: 81,
      name: "Good Will Hunting",
      releaseDate: 1997,
      length: "2h 6m",
      rating: 8.3,
      director: "Gus Van Sant",
      genre: "Drama",
      description:
        "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
    },
    {
      rank: 82,
      name: "Once Upon a Time in America",
      releaseDate: 1984,
      length: "3h 49m",
      rating: 8.3,
      director: "Sergio Leone",
      genre: "Crime, Drama",
      description:
        "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan 35 years later, where he must once again confront the ghosts and regrets of his old life.",
    },
    {
      rank: 83,
      name: "Your Name.",
      releaseDate: 2016,
      length: "1h 46m",
      rating: 8.4,
      director: "Makoto Shinkai",
      genre: "Animation, Drama, Fantasy",
      description:
        "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
    },
    {
      rank: 84,
      name: "3 Idiots",
      releaseDate: 2009,
      length: "2h 50m",
      rating: 8.4,
      director: "Rajkumar Hirani",
      genre: "Comedy, Drama",
      description:
        "Two friends are searching for their long-lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
    },
    {
      rank: 85,
      name: "Singin' in the Rain",
      releaseDate: 1952,
      length: "1h 43m",
      rating: 8.3,
      director: "Stanley Donen",
      genre: "Comedy, Musical, Romance",
      description:
        "A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.",
    },
    {
      rank: 86,
      name: "High and Low",
      releaseDate: 1963,
      length: "2h 23m",
      rating: 8.4,
      director: "Akira Kurosawa",
      genre: "Crime, Drama, Mystery",
      description:
        "An executive of a Yokohama shoe company becomes a victim of extortion when his chauffeur's son is kidnapped by mistake and held for ransom.",
    },
    {
      rank: 87,
      name: "Requiem for a Dream",
      releaseDate: 2000,
      length: "1h 42m",
      rating: 8.3,
      director: "Darren Aronofsky",
      genre: "Drama",
      description:
        "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
    },
    {
      rank: 88,
      name: "Capernaum",
      releaseDate: 2018,
      length: "2h 6m",
      rating: 8.4,
      director: "Nadine Labaki",
      genre: "Drama",
      description:
        "While serving a five-year sentence for a violent crime, a 12-year-old boy sues his parents for neglect.",
    },
    {
      rank: 89,
      name: "Toy Story 3",
      releaseDate: 2010,
      length: "1h 43m",
      rating: 8.3,
      director: "Lee Unkrich",
      genre: "Animation, Adventure, Comedy",
      description:
        "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.",
    },
    {
      rank: 90,
      name: "Star Wars: Return of the Jedi",
      releaseDate: 1983,
      length: "2h 11m",
      rating: 8.3,
      director: "Richard Marquand",
      genre: "Action, Adventure, Fantasy",
      description:
        "After rescuing Han Solo from Jabba the Hutt, the Rebels attempt to destroy the second Death Star, while Luke struggles to help Darth Vader back from the dark side.",
    },
    {
      rank: 91,
      name: "Come and See",
      releaseDate: 1985,
      length: "2h 22m",
      rating: 8.4,
      director: "Elem Klimov",
      genre: "Drama, War",
      description:
        "After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.",
    },
    {
      rank: 92,
      name: "Eternal Sunshine of the Spotless Mind",
      releaseDate: 2004,
      length: "1h 48m",
      rating: 8.3,
      director: "Michel Gondry",
      genre: "Drama, Romance, Sci-Fi",
      description:
        "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.",
    },
    {
      rank: 93,
      name: "2001: A Space Odyssey",
      releaseDate: 1968,
      length: "2h 29m",
      rating: 8.3,
      director: "Stanley Kubrick",
      genre: "Adventure, Sci-Fi",
      description:
        "After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins - a spacecraft manned by two men and the supercomputer H.A.L. 9000.",
    },
    {
      rank: 94,
      name: "The Hunt",
      releaseDate: 2012,
      length: "1h 55m",
      rating: 8.3,
      director: "Thomas Vinterberg",
      genre: "Drama",
      description:
        "A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.",
    },
    {
      rank: 95,
      name: "Reservoir Dogs",
      releaseDate: 1992,
      length: "1h 39m",
      rating: 8.3,
      director: "Quentin Tarantino",
      genre: "Crime, Drama, Thriller",
      description:
        "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.",
    },
    {
      rank: 96,
      name: "Lawrence of Arabia",
      releaseDate: 1962,
      length: "3h 38m",
      rating: 8.3,
      director: "David Lean",
      genre: "Adventure, Biography, Drama",
      description:
        "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.",
    },
    {
      rank: 97,
      name: "Citizen Kane",
      releaseDate: 1941,
      length: "1h 59m",
      rating: 8.3,
      director: "Orson Welles",
      genre: "Drama, Mystery",
      description:
        "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'",
    },
    {
      rank: 98,
      name: "Ikiru",
      releaseDate: 1952,
      length: "2h 23m",
      rating: 8.3,
      director: "Akira Kurosawa",
      genre: "Drama",
      description:
        "A bureaucrat tries to find meaning in his life after he discovers he has terminal cancer.",
    },
    {
      rank: 99,
      name: "M",
      releaseDate: 1931,
      length: "1h 57m",
      rating: 8.3,
      director: "Fritz Lang",
      genre: "Crime, Drama, Mystery",
      description:
        "When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.",
    },
    {
      rank: 100,
      name: "North by Northwest",
      releaseDate: 1959,
      length: "2h 16m",
      rating: 8.3,
      director: "Alfred Hitchcock",
      genre: "Adventure, Mystery, Thriller",
      description:
        "A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.",
    },
    {
      rank: 101,
      name: 'The Apartment',
      releaseDate: '1960',
      length: '2h 5m',
      rating: 8.3,
      director: 'Billy Wilder',
      genre: 'Drama',
      description: 'A Manhattan insurance clerk tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.',
    },
    {
      rank: 102,
      name: 'Vertigo',
      releaseDate: '1958',
      length: '2h 8m',
      rating: 8.3,
      director: 'Alfred Hitchcock',
      genre: 'Mystery',
      description: 'A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.',
    },
    {
      rank: 103,
      name: 'Amélie',
      releaseDate: '2001',
      length: '2h 2m',
      rating: 8.3,
      director: 'Jean-Pierre Jeunet',
      genre: 'Romance',
      description: "Despite being caught in her imaginative world, Amelie, a young waitress, decides to help people find happiness. Her quest to spread joy leads her on a journey where she finds true love.",
    },
    {
      rank: 104,
      name: 'Double Indemnity',
      releaseDate: '1944',
      length: '1h 47m',
      rating: 8.3,
      director: 'Billy Wilder',
      genre: 'Crime',
      description: 'A Los Angeles insurance representative lets an alluring housewife seduce him into a scheme of insurance fraud and murder that arouses the suspicion of his colleague, an insurance investigator.',
    },
    {
      rank: 105,
      name: 'A Clockwork Orange',
      releaseDate: '1971',
      length: '2h 16m',
      rating: 8.3,
      director: 'Stanley Kubrick',
      genre: 'Crime',
      description: "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.",
    },
    {
      rank: 106,
      name: 'Full Metal Jacket',
      releaseDate: '1987',
      length: '1h 56m',
      rating: 8.3,
      director: 'Stanley Kubrick',
      genre: 'Drama',
      description: 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.',
    },
    {
      rank: 107,
      name: 'Scarface',
      releaseDate: '1983',
      length: '2h 50m',
      rating: 8.3,
      director: 'Brian De Palma',
      genre: 'Crime',
      description: 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.',
    },
    {
      rank: 108,
      name: 'Hamilton',
      releaseDate: '2020',
      length: '2h 40m',
      rating: 8.3,
      director: 'Thomas Kail',
      genre: 'Biography',
      description: "The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.",
    },
    {
      rank: 109,
      name: 'Incendies',
      releaseDate: '2010',
      length: '2h 11m',
      rating: 8.3,
      director: 'Denis Villeneuve',
      genre: 'Drama',
      description: "Twins journey to the Middle East to discover their family history and fulfill their mother's last wishes.",
    },
    {
      rank: 110,
      name: 'Heat',
      releaseDate: '1995',
      length: '2h 50m',
      rating: 8.3,
      director: 'Michael Mann',
      genre: 'Crime',
      description: 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.',
    },
    {
      rank: 111,
      name: 'Up',
      releaseDate: '2009',
      length: '1h 36m',
      rating: 8.3,
      director: 'Pete Docter',
      genre: 'Animation',
      description: '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.',
    },
    {
      rank: 112,
      name: 'To Kill a Mockingbird',
      releaseDate: '1962',
      length: '2h 9m',
      rating: 8.3,
      director: 'Robert Mulligan',
      genre: 'Drama',
      description: 'Atticus Finch, a widowed lawyer in Depression-era Alabama, defends a Black man against an undeserved rape charge and tries to educate his young children against prejudice.',
    },
    {
      rank: 113,
      name: 'The Sting',
      releaseDate: '1973',
      length: '2h 9m',
      rating: 8.3,
      director: 'George Roy Hill',
      genre: 'Comedy',
      description: 'Two grifters team up to pull off the ultimate con.',
    },
    {
      rank: 114,
      name: 'A Separation',
      releaseDate: '2011',
      length: '2h 3m',
      rating: 8.3,
      director: 'Asghar Farhadi',
      genre: 'Drama',
      description: 'A married couple is faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer\'s disease.',
    },
    {
      rank: 115,
      name: 'Metropolis',
      releaseDate: '1927',
      length: '2h 33m',
      rating: 8.3,
      director: 'Fritz Lang',
      genre: 'Drama',
      description: 'In a futuristic city sharply divided between the working class and the city planners, the son of the city\'s mastermind falls in love with a working-class prophet who predicts the coming of a savior to mediate their differences.',
    },
    {
      rank: 116,
      name: 'Die Hard',
      releaseDate: '1988',
      length: '2h 12m',
      rating: 8.2,
      director: 'John McTiernan',
      genre: 'Action',
      description: 'A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.',
    },
    {
      rank: 117,
      name: 'Indiana Jones and the Last Crusade',
      releaseDate: '1989',
      length: '2h 7m',
      rating: 8.2,
      director: 'Steven Spielberg',
      genre: 'Action',
      description: 'In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones finds himself up against the Nazis again to stop them from obtaining its powers.',
    },
    {
      rank: 118,
      name: 'L.A. Confidential',
      releaseDate: '1997',
      length: '2h 18m',
      rating: 8.2,
      director: 'Curtis Hanson',
      genre: 'Crime',
      description: 'As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.',
    },
    {
      rank: 119,
      name: 'Snatch',
      releaseDate: '2000',
      length: '1h 44m',
      rating: 8.2,
      director: 'Guy Ritchie',
      genre: 'Comedy',
      description: 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.',
    },
    {
      rank: 120,
      name: 'Bicycle Thieves',
      releaseDate: '1948',
      length: '1h 29m',
      rating: 8.3,
      director: 'Vittorio De Sica',
      genre: 'Drama',
      description: 'In post-war Italy, a working-class man\'s bicycle is stolen, endangering his efforts to find work. He and his son set out to find it.',
    },
    {
      rank: 121,
      name: 'Taxi Driver',
      releaseDate: '1976',
      length: '1h 54m',
      rating: 8.2,
      director: 'Martin Scorsese',
      genre: 'Drama',
      description: 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.',
    },
    {
      rank: 122,
      name: 'Like Stars on Earth',
      releaseDate: '2007',
      length: '2h 45m',
      rating: 8.3,
      director: 'Aamir Khan',
      genre: 'Drama',
      description: 'An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.',
    },
    {
      rank: 123,
      name: '1917',
      releaseDate: '2019',
      length: '1h 59m',
      rating: 8.2,
      director: 'Sam Mendes',
      genre: 'Drama',
      description: 'April 6th, 1917. As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.',
    },
    {
      rank: 124,
      name: 'Dangal',
      releaseDate: '2016',
      length: '2h 41m',
      rating: 8.3,
      director: 'Nitesh Tiwari',
      genre: 'Biography',
      description: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    },
    {
      rank: 125,
      name: 'Downfall',
      releaseDate: '2004',
      length: '2h 36m',
      rating: 8.2,
      director: 'Oliver Hirschbiegel',
      genre: 'Biography',
      description: 'Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator\'s final days in his Berlin bunker at the end of WWII.',
    },
    {
      rank: 126,
      name: 'Top Gun: Maverick',
      releaseDate: '2022',
      length: '2h 10m',
      rating: 8.3,
      director: 'Joseph Kosinski',
      genre: 'Action',
      description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.',
    },
    {
      rank: 127,
      name: 'For a Few Dollars More',
      releaseDate: '1965',
      length: '2h 12m',
      rating: 8.2,
      director: 'Sergio Leone',
      genre: 'Western',
      description: 'Two bounty hunters with the same intentions team up to track down an escaped Mexican outlaw.',
    },
    {
      rank: 128,
      name: 'Batman Begins',
      releaseDate: '2005',
      length: '2h 20m',
      rating: 8.2,
      director: 'Christopher Nolan',
      genre: 'Action',
      description: 'After witnessing his parents\' death, Bruce learns the art of fighting to confront injustice. When he returns to Gotham as Batman, he must stop a secret society that intends to destroy the city.',
    },
    {
      rank: 129,
      name: 'The Kid',
      releaseDate: '1921',
      length: '1h 8m',
      rating: 8.3,
      director: 'Charles Chaplin',
      genre: 'Comedy',
      description: 'The Tramp cares for an abandoned child, but events put their relationship in jeopardy.',
    },
    {
      rank: 130,
      name: 'Some Like It Hot',
      releaseDate: '1959',
      length: '2h 1m',
      rating: 8.2,
      director: 'Billy Wilder',
      genre: 'Comedy',
      description: 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.',
    },
    {
      rank: 131,
      name: 'The Father',
      releaseDate: '2020',
      length: '1h 37m',
      rating: 8.2,
      director: 'Florian Zeller',
      genre: 'Drama',
      description: 'A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.',
    },
    {
      rank: 132,
      name: 'The Wolf of Wall Street',
      releaseDate: '2013',
      length: '3h',
      rating: 8.2,
      director: 'Martin Scorsese',
      genre: 'Biography',
      description: 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.',
    },
    {
      rank: 133,
      name: 'All About Eve',
      releaseDate: '1950',
      length: '2h 18m',
      rating: 8.2,
      director: 'Joseph L. Mankiewicz',
      genre: 'Drama',
      description: 'A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.',
    },
    {
      rank: 134,
      name: 'Green Book',
      releaseDate: '2018',
      length: '2h 10m',
      rating: 8.2,
      director: 'Peter Farrelly',
      genre: 'Biography',
      description: 'A working-class Italian-American bouncer becomes the driver for an African-American classical pianist on a tour of venues through the 1960s American South.',
    },
    {
      rank: 135,
      name: 'Judgment at Nuremberg',
      releaseDate: '1961',
      length: '2h 59m',
      rating: 8.3,
      director: 'Stanley Kramer',
      genre: 'Drama',
      description: 'In 1948, an American court in occupied Germany tries four Nazis judged for war crimes.',
    },
    {
      rank: 136,
      name: 'The Truman Show',
      releaseDate: '1998',
      length: '1h 43m',
      rating: 8.2,
      director: 'Peter Weir',
      genre: 'Comedy',
      description: 'An insurance salesman discovers his whole life is actually a reality TV show.',
    },
    {
      rank: 137,
      name: 'Ran',
      releaseDate: '1985',
      length: '2h 42m',
      rating: 8.2,
      director: 'Akira Kurosawa',
      genre: 'Action',
      description: 'In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, he vastly underestimates how the new-found power will corrupt them and cause them to turn on each other...and him.',
    },
    {
      rank: 138,
      name: 'Casino',
      releaseDate: '1995',
      length: '2h 58m',
      rating: 8.2,
      director: 'Martin Scorsese',
      genre: 'Crime',
      description: 'In Las Vegas, two best friends - a mafia enforcer and a casino executive - compete for a gambling empire and a fast-living, fast-loving socialite.',
    },
    {
      rank: 139,
      name: 'There Will Be Blood',
      releaseDate: '2007',
      length: '2h 38m',
      rating: 8.2,
      director: 'Paul Thomas Anderson',
      genre: 'Drama',
      description: 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.',
    },
    {
      rank: 140,
      name: 'Pan\'s Labyrinth',
      releaseDate: '2006',
      length: '1h 58m',
      rating: 8.2,
      director: 'Guillermo del Toro',
      genre: 'Drama',
      description: 'In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.',
    },
    {
      rank: 141,
      name: 'Shutter Island',
      releaseDate: '2010',
      length: '2h 18m',
      rating: 8.2,
      director: 'Martin Scorsese',
      genre: 'Mystery, Thriller',
      description: 'Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.',
    },
    {
      rank: 142,
      name: 'Unforgiven',
      releaseDate: '1992',
      length: '2h 10m',
      rating: 8.2,
      director: 'Clint Eastwood',
      genre: 'Drama, Western',
      description: 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man, The "Schofield Kid."',
    },
    {
      rank: 143,
      name: 'The Sixth Sense',
      releaseDate: '1999',
      length: '1h 47m',
      rating: 8.2,
      director: 'M. Night Shyamalan',
      genre: 'Drama, Mystery, Thriller',
      description: 'Malcolm Crowe, a child psychologist, starts treating a young boy, Cole, who encounters dead people and convinces him to help them. In turn, Cole helps Malcolm reconcile with his estranged wife.',
    },
    {
      rank: 144,
      name: 'Jurassic Park',
      releaseDate: '1993',
      length: '2h 7m',
      rating: 8.2,
      director: 'Steven Spielberg',
      genre: 'Action, Adventure, Sci-Fi',
      description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    },
    {
      rank: 145,
      name: 'A Beautiful Mind',
      releaseDate: '2001',
      length: '2h 15m',
      rating: 8.2,
      director: 'Ron Howard',
      genre: 'Biography, Drama',
      description: 'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.',
    },
    {
      rank: 146,
      name: 'The Treasure of the Sierra Madre',
      releaseDate: '1948',
      length: '2h 6m',
      rating: 8.2,
      director: 'John Huston',
      genre: 'Adventure, Drama, Western',
      description: 'Two down-on-their-luck Americans searching for work in 1920s Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.',
    },
    {
      rank: 147,
      name: 'Yojimbo',
      releaseDate: '1961',
      length: '1h 50m',
      rating: 8.2,
      director: 'Akira Kurosawa',
      genre: 'Action, Drama',
      description: 'A crafty ronin comes to a town divided by two criminal gangs and decides to play them against each other to free the town.',
    },
    {
      rank: 148,
      name: 'Monty Python and the Holy Grail',
      releaseDate: '1975',
      length: '1h 31m',
      rating: 8.2,
      director: 'Terry Gilliam',
      genre: 'Adventure, Comedy, Fantasy',
      description: 'King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail, encountering many very silly obstacles.',
    },
    {
      rank: 149,
      name: 'No Country for Old Men',
      releaseDate: '2007',
      length: '2h 2m',
      rating: 8.2,
      director: 'Ethan Coen',
      genre: 'Crime, Drama, Thriller',
      description: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.',
    },
    {
      rank: 150,
      name: 'Kill Bill: Vol. 1',
      releaseDate: '2003',
      length: '1h 51m',
      rating: 8.2,
      director: 'Quentin Tarantino',
      genre: 'Action, Crime, Thriller',
      description: 'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.',
    },
    {
      rank: 151,
      name: 'The Great Escape',
      releaseDate: '1963',
      length: '2h 52m',
      rating: 8.2,
      director: 'John Sturges',
      genre: 'Adventure, Drama, History',
      description: 'Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II.',
    },
    {
      rank: 152,
      name: 'Rashomon',
      releaseDate: '1950',
      length: '1h 28m',
      rating: 8.2,
      director: 'Akira Kurosawa',
      genre: 'Crime, Drama, Mystery',
      description: 'The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai\'s ghost, and a woodcutter.',
    },
    {
      rank: 153,
      name: 'The Thing',
      releaseDate: '1982',
      length: '1h 49m',
      rating: 8.2,
      director: 'John Carpenter',
      genre: 'Horror, Mystery, Sci-Fi',
      description: 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.',
    },
    {
      rank: 154,
      name: 'Finding Nemo',
      releaseDate: '2003',
      length: '1h 40m',
      rating: 8.2,
      director: 'Andrew Stanton',
      genre: 'Animation, Adventure, Comedy',
      description: 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.',
    },
    {
      rank: 155,
      name: 'Spider-Man: No Way Home',
      releaseDate: '2021',
      length: '2h 28m',
      rating: 8.2,
      director: 'Jon Watts',
      genre: 'Action, Adventure, Fantasy',
      description: 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.',
    },
    {
      rank: 156,
      name: 'The Elephant Man',
      releaseDate: '1980',
      length: '2h 4m',
      rating: 8.2,
      director: 'David Lynch',
      genre: 'Biography, Drama',
      description: 'A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak. Behind his monstrous facade, there is revealed a person of kindness, intelligence, and sophistication.',
    },
    {
      rank: 157,
      name: 'Chinatown',
      releaseDate: '1974',
      length: '2h 10m',
      rating: 8.2,
      director: 'Roman Polanski',
      genre: 'Drama, Mystery, Thriller',
      description: 'A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.',
    },
    {
      rank: 158,
      name: 'Raging Bull',
      releaseDate: '1980',
      length: '2h 9m',
      rating: 8.1,
      director: 'Martin Scorsese',
      genre: 'Biography, Drama, Sport',
      description: 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.',
    },
    {
      rank: 159,
      name: 'V for Vendetta',
      releaseDate: '2005',
      length: '2h 12m',
      rating: 8.2,
      director: 'James McTeigue',
      genre: 'Action, Drama, Sci-Fi',
      description: 'In a future British dystopian society, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow the tyrannical government - with the help of a young woman.',
    },
    {
      rank: 160,
      name: 'Gone with the Wind',
      releaseDate: '1939',
      length: '3h 58m',
      rating: 8.2,
      director: 'Victor Fleming',
      genre: 'Drama, History, Romance',
      description: 'A sheltered and manipulative Southern belle and a roguish profiteer face off in a turbulent romance as the society around them crumbles with the end of slavery and is rebuilt during the Civil War and Reconstruction periods.',
    },
    {
      rank: 161,
      name: 'Dial M for Murder',
      releaseDate: '1954',
      length: '1h 45m',
      rating: 8.2,
      director: 'Alfred Hitchcock',
      genre: 'Crime, Thriller',
      description: 'A former tennis star arranges the murder of his adulterous wife.',
    },
    {
      rank: 162,
      name: "Howl's Moving Castle",
      releaseDate: '2004',
      length: '1h 59m',
      rating: 8.2,
      director: 'Hayao Miyazaki',
      genre: 'Animation, Adventure, Family',
      description: 'When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.',
    },
    {
      rank: 163,
      name: 'Lock, Stock and Two Smoking Barrels',
      releaseDate: '1998',
      length: '1h 47m',
      rating: 8.1,
      director: 'Guy Ritchie',
      genre: 'Comedy, Crime',
      description: "Eddy persuades his three pals to pool money for a vital poker game against a powerful local mobster, Hatchet Harry. Eddy loses, after which Harry gives him a week to pay back 500,000 pounds.",
    },
    {
      rank: 164,
      name: 'Inside Out',
      releaseDate: '2015',
      length: '1h 35m',
      rating: 8.1,
      director: 'Pete Docter',
      genre: 'Animation, Adventure, Comedy',
      description: 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust, and Sadness - conflict on how best to navigate a new city, house, and school.',
    },
    {
      rank: 165,
      name: 'The Secret in Their Eyes',
      releaseDate: '2009',
      length: '2h 9m',
      rating: 8.2,
      director: 'Juan José Campanella',
      genre: 'Drama, Mystery, Thriller',
      description: 'A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior - both of which still haunt him decades later.',
    },
    {
      rank: 166,
      name: 'Three Billboards Outside Ebbing, Missouri',
      releaseDate: '2017',
      length: '1h 55m',
      rating: 8.1,
      director: 'Martin McDonagh',
      genre: 'Crime, Drama',
      description: 'A mother personally challenges the local authorities to solve her daughter\'s murder when they fail to catch the culprit.',
    },
    {
      rank: 167,
      name: 'Prisoners',
      releaseDate: '2013',
      length: '2h 33m',
      rating: 8.1,
      director: 'Denis Villeneuve',
      genre: 'Crime, Drama, Mystery',
      description: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
    },
    {
      rank: 168,
      name: 'Trainspotting',
      releaseDate: '1996',
      length: '1h 33m',
      rating: 8.1,
      director: 'Danny Boyle',
      genre: 'Drama',
      description: 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.',
    },
    {
      rank: 169,
      name: 'The Bridge on the River Kwai',
      releaseDate: '1957',
      length: '2h 41m',
      rating: 8.1,
      director: 'David Lean',
      genre: 'Adventure, Drama, War',
      description: 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors in occupied Burma, not knowing that the allied forces are planning a daring commando raid through the jungle to destroy it.',
    },
    {
      rank: 170,
      name: 'Guardians of the Galaxy Vol. 3',
      releaseDate: '2023',
      length: '2h 30m',
      rating: 8.2,
      director: 'James Gunn',
      genre: 'Action, Adventure, Comedy',
      description: 'Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.',
    },
    {
      rank: 171,
      name: 'Fargo',
      releaseDate: '1996',
      length: '1h 38m',
      rating: 8.1,
      director: 'Joel Coen',
      genre: 'Crime, Drama, Thriller',
      description: "Minnesota car salesman Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the quite pregnant Marge Gunderson.",
    },
    {
      rank: 172,
      name: 'Warrior',
      releaseDate: '2011',
      length: '2h 20m',
      rating: 8.1,
      director: 'Gavin O\'Connor',
      genre: 'Drama, Sport',
      description: 'The youngest son of an alcoholic former boxer returns home, where he\'s trained by his father for competition in a mixed martial arts tournament - a path that puts the fighter on a collision course with his estranged, older brother.',
    },
    {
      rank: 173,
      name: 'Gran Torino',
      releaseDate: '2008',
      length: '1h 56m',
      rating: 8.1,
      director: 'Clint Eastwood',
      genre: 'Drama',
      description: 'After a Hmong teenager tries to steal his prized 1972 Gran Torino, a disgruntled, prejudiced Korean War veteran seeks to redeem both the boy and himself.',
    },
    {
      rank: 174,
      name: 'Catch Me If You Can',
      releaseDate: '2002',
      length: '2h 21m',
      rating: 8.1,
      director: 'Steven Spielberg',
      genre: 'Biography, Crime, Drama',
      description: 'Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer, and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.',
    },
    {
      rank: 175,
      name: 'My Neighbour Totoro',
      releaseDate: '1988',
      length: '1h 26m',
      rating: 8.1,
      director: 'Hayao Miyazaki',
      genre: 'Animation, Family, Fantasy',
      description: 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.',
    },
    {
      rank: 176,
      name: 'Million Dollar Baby',
      releaseDate: '2004',
      length: '2h 12m',
      rating: 8.1,
      director: 'Clint Eastwood',
      genre: 'Drama, Sport',
      description: 'Frankie, an ill-tempered old coach, reluctantly agrees to train aspiring boxer Maggie. Impressed with her determination and talent, he helps her become the best, and the two soon form a close bond.',
    },
    {
      rank: 177,
      name: 'Children of Heaven',
      releaseDate: '1997',
      length: '1h 29m',
      rating: 8.2,
      director: 'Majid Majidi',
      genre: 'Drama, Family',
      description: 'After a boy loses his sister\'s pair of shoes, he goes on a series of adventures in order to find them. When he can\'t, he tries a new way to "win" a new pair.',
    },
    {
      rank: 178,
      name: 'Klaus',
      releaseDate: '2019',
      length: '1h 36m',
      rating: 8.2,
      director: 'Sergio Pablos',
      genre: 'Animation, Adventure, Comedy',
      description: "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
    },
    {
      rank: 179,
      name: 'Blade Runner',
      releaseDate: '1982',
      length: '1h 57m',
      rating: 8.1,
      director: 'Ridley Scott',
      genre: 'Action, Sci-Fi, Thriller',
      description: 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.',
    },
    {
      rank: 180,
      name: 'Harry Potter and the Deathly Hallows: Part 2',
      releaseDate: '2011',
      length: '2h 10m',
      rating: 8.1,
      director: 'David Yates',
      genre: 'Adventure, Drama, Fantasy',
      description: 'Harry, Ron, and Hermione search for Voldemort\'s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.',
    },
    {
      rank: 181,
      name: 'The Gold Rush',
      releaseDate: '1925',
      length: '1h 35m',
      rating: 8.1,
      director: 'Charles Chaplin',
      genre: 'Adventure, Comedy, Drama',
      description: 'A prospector goes to the Klondike during the 1890s gold rush in hopes of making his fortune, and is smitten with a girl he sees in a dance hall.',
    },
    {
      rank: 182,
      name: '12 Years a Slave',
      releaseDate: '2013',
      length: '2h 14m',
      rating: 8.1,
      director: 'Steve McQueen',
      genre: 'Biography, Drama, History',
      description: 'In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.',
    },
    {
      rank: 183,
      name: 'Before Sunrise',
      releaseDate: '1995',
      length: '1h 41m',
      rating: 8.1,
      director: 'Richard Linklater',
      genre: 'Drama, Romance',
      description: 'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.',
    },
    {
      rank: 184,
      name: 'The Grand Budapest Hotel',
      releaseDate: '2014',
      length: '1h 39m',
      rating: 8.1,
      director: 'Wes Anderson',
      genre: 'Adventure, Comedy, Crime',
      description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    },
    {
      rank: 185,
      name: 'Ben-Hur',
      releaseDate: '1959',
      length: '3h 32m',
      rating: 8.1,
      director: 'William Wyler',
      genre: 'Adventure, Drama, History',
      description: 'After a Jewish prince is betrayed and sent into slavery by a Roman friend in 1st-century Jerusalem, he regains his freedom and comes back for revenge.',
    },
    {
      rank: 186,
      name: 'Gone Girl',
      releaseDate: '2014',
      length: '2h 29m',
      rating: 8.1,
      director: 'David Fincher',
      genre: 'Crime, Drama, Mystery',
      description: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    },
    {
      rank: 187,
      name: 'On the Waterfront',
      releaseDate: '1954',
      length: '1h 48m',
      rating: 8.1,
      director: 'Elia Kazan',
      genre: 'Crime, Drama, Thriller',
      description: 'An ex-prize fighter turned New Jersey longshoreman struggles to stand up to his corrupt union bosses, including his older brother, as he starts to connect with the grieving sister of one of the syndicate\'s victims.',
    },
    {
      rank: 188,
      name: 'Barry Lyndon',
      releaseDate: '1975',
      length: '3h 5m',
      rating: 8.1,
      director: 'Stanley Kubrick',
      genre: 'Adventure, Drama, History',
      description: 'An Irish rogue wins the heart of a rich widow and assumes her dead husband\'s aristocratic position in 18th-century England.',
    },
    {
      rank: 189,
      name: 'The General',
      releaseDate: '1926',
      length: '1h 18m',
      rating: 8.1,
      director: 'Clyde Bruckman',
      genre: 'Action, Adventure, Comedy',
      description: 'After being rejected by the Confederate military, not realizing it was due to his crucial civilian role, an engineer must single-handedly recapture his beloved locomotive after it is seized by Union spies and return it through enemy lines.',
    },
    {
      rank: 190,
      name: 'Wild Strawberries',
      releaseDate: '1957',
      length: '1h 31m',
      rating: 8.1,
      director: 'Ingmar Bergman',
      genre: 'Drama, Romance',
      description: 'After living a life marked by coldness, an aging professor is forced to confront the emptiness of his existence.',
    },
    {
      rank: 191,
      name: 'In the Name of the Father',
      releaseDate: '1993',
      length: '2h 13m',
      rating: 8.1,
      director: 'Jim Sheridan',
      genre: 'Biography, Drama',
      description: "A man's coerced confession to an I.R.A. bombing he did not commit results in the imprisonment of his father as well. An English lawyer fights to free them.",
    },
    {
      rank: 192,
      name: 'The Deer Hunter',
      releaseDate: '1978',
      length: '3h 3m',
      rating: 8.1,
      director: 'Michael Cimino',
      genre: 'Drama, War',
      description: 'An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of several friends in a small steel mill town in Pennsylvania.',
    },
    {
      rank: 193,
      name: 'Hacksaw Ridge',
      releaseDate: '2016',
      length: '2h 19m',
      rating: 8.1,
      director: 'Mel Gibson',
      genre: 'Biography, Drama, History',
      description: "World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
    },
    {
      rank: 194,
      name: 'The Third Man',
      releaseDate: '1949',
      length: '1h 44m',
      rating: 8.1,
      director: 'Carol Reed',
      genre: 'Film-Noir, Mystery, Thriller',
      description: 'Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.',
    },
    {
      rank: 195,
      name: 'Memories of Murder',
      releaseDate: '2003',
      length: '2h 11m',
      rating: 8.1,
      director: 'Bong Joon Ho',
      genre: 'Crime, Drama, Mystery',
      description: 'In a small Korean province in 1986, two detectives struggle with the case of multiple young women being found raped and murdered by an unknown culprit.',
    },
    {
      rank: 196,
      name: 'The Wages of Fear',
      releaseDate: '1953',
      length: '2h 11m',
      rating: 8.2,
      director: 'Henri-Georges Clouzot',
      genre: 'Adventure, Drama, Thriller',
      description: 'In a decrepit South American village, four men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe.',
    },
    {
      rank: 197,
      name: 'Sherlock Jr.',
      releaseDate: '1924',
      length: '45m',
      rating: 8.2,
      director: 'Buster Keaton',
      genre: 'Action, Comedy, Romance',
      description: "A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend's father's pocketwatch.",
    },
    {
      rank: 198,
      name: 'Wild Tales',
      releaseDate: '2014',
      length: '2h 2m',
      rating: 8.1,
      director: 'Damián Szifron',
      genre: 'Comedy, Drama, Thriller',
      description: 'Six short stories that explore the extremities of human behavior involving people in distress.',
    },
    {
      rank: 199,
      name: 'Mr. Smith Goes to Washington',
      releaseDate: '1939',
      length: '2h 9m',
      rating: 8.1,
      director: 'Frank Capra',
      genre: 'Drama',
      description: 'A naive youth leader is appointed to fill a vacancy in the U.S. Senate. His idealistic plans promptly collide with corruption at home and subterfuge from his hero in Washington, but he tries to forge ahead despite attacks on his character.',
    },
    {
      rank: 200,
      name: 'Mad Max: Fury Road',
      releaseDate: '2015',
      length: '2h',
      rating: 8.1,
      director: 'George Miller',
      genre: 'Action, Adventure, Sci-Fi',
      description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    },
    {
      rank: 201,
      name: 'Mary and Max',
      releaseDate: '2009',
      length: '1h 32m',
      rating: 8.1,
      director: 'Adam Elliot',
      genre: 'Animation, Comedy, Drama',
      description: 'A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.',
    },
    {
      rank: 202,
      name: 'Dead Poets Society',
      releaseDate: '1989',
      length: '2h 8m',
      rating: 8.1,
      director: 'Peter Weir',
      genre: 'Comedy, Drama',
      description: 'Maverick teacher John Keating uses poetry to embolden his boarding school students to new heights of self-expression.',
    },
    {
      rank: 203,
      name: 'Monsters, Inc.',
      releaseDate: '2001',
      length: '1h 32m',
      rating: 8.1,
      director: 'Pete Docter',
      genre: 'Animation, Adventure, Comedy',
      description: "In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.",
    },
    {
      rank: 204,
      name: 'How to Train Your Dragon',
      releaseDate: '2010',
      length: '1h 38m',
      rating: 8.1,
      director: 'Dean DeBlois',
      genre: 'Animation, Action, Adventure',
      description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.",
    },
    {
      rank: 205,
      name: 'The Seventh Seal',
      releaseDate: '1957',
      length: '1h 36m',
      rating: 8.1,
      director: 'Ingmar Bergman',
      genre: 'Drama, Fantasy',
      description: "A knight returning to Sweden after the Crusades seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.",
    },
    {
      rank: 206,
      name: 'Jaws',
      releaseDate: '1975',
      length: '2h 4m',
      rating: 8.1,
      director: 'Steven Spielberg',
      genre: 'Adventure, Drama, Thriller',
      description: "When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
    },
    {
      rank: 207,
      name: 'Room',
      releaseDate: '2015',
      length: '1h 58m',
      rating: 8.1,
      director: 'Lenny Abrahamson',
      genre: 'Drama, Thriller',
      description: "A little boy is held captive in a room with his mother since his birth, so he has never known the world outside.",
    },
    {
      rank: 208,
      name: 'The Big Lebowski',
      releaseDate: '1998',
      length: '1h 57m',
      rating: 8.1,
      director: 'Joel Coen',
      genre: 'Comedy, Crime',
      description: "Jeff 'The Dude' Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.",
    },
    {
      rank: 209,
      name: 'Tokyo Story',
      releaseDate: '1953',
      length: '2h 16m',
      rating: 8.2,
      director: 'Yasujirô Ozu',
      genre: 'Drama',
      description: "An old couple visit their children and grandchildren in the city, but receive little attention.",
    },
    {
      rank: 210,
      name: "Le Mans '66",
      releaseDate: '2019',
      length: '2h 32m',
      rating: 8.1,
      director: 'James Mangold',
      genre: 'Action, Biography, Drama',
      description: "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
    },
    {
      rank: 211,
      name: 'The Passion of Joan of Arc',
      releaseDate: '1928',
      length: '1h 50m',
      rating: 8.2,
      director: 'Carl Theodor Dreyer',
      genre: 'Biography, Drama, History',
      description: "In 1431, Jeanne d'Arc is placed on trial on charges of heresy. The ecclesiastical jurists attempt to force Jeanne to recant her claims of holy visions.",
    },
    {
      rank: 212,
      name: 'Hotel Rwanda',
      releaseDate: '2004',
      length: '2h 1m',
      rating: 8.1,
      director: 'Terry George',
      genre: 'Biography, Drama, History',
      description: "Paul Rusesabagina, a hotel manager, houses over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda, Africa.",
    },
    {
      rank: 213,
      name: 'Ratatouille',
      releaseDate: '2007',
      length: '1h 51m',
      rating: 8.1,
      director: 'Brad Bird',
      genre: 'Animation, Adventure, Comedy',
      description: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
    },
    {
      rank: 214,
      name: 'Rocky',
      releaseDate: '1976',
      length: '2h',
      rating: 8.1,
      director: 'John G. Avildsen',
      genre: 'Drama, Sport',
      description: "A small-time Philadelphia boxer gets a supremely rare chance to fight the world heavyweight champion in a bout in which he strives to go the distance for his self-respect.",
    },
    {
      rank: 215,
      name: 'Platoon',
      releaseDate: '1986',
      length: '2h',
      rating: 8.1,
      director: 'Oliver Stone',
      genre: 'Drama, War',
      description: "Chris Taylor, a neophyte recruit in Vietnam, finds himself caught in a battle of wills between two sergeants, one good and the other evil. A shrewd examination of the brutality of war and the duality of man in conflict.",
    },
    {
      rank: 216,
      name: 'Logan',
      releaseDate: '2017',
      length: '2h 17m',
      rating: 8.1,
      director: 'James Mangold',
      genre: 'Action, Drama, Sci-Fi',
      description: "In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.",
    },
    {
      rank: 217,
      name: 'Spotlight',
      releaseDate: '2015',
      length: '2h 9m',
      rating: 8.1,
      director: 'Tom McCarthy',
      genre: 'Biography, Crime, Drama',
      description: "The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.",
    },
    {
      rank: 218,
      name: 'The Terminator',
      releaseDate: '1984',
      length: '1h 47m',
      rating: 8.1,
      director: 'James Cameron',
      genre: 'Action, Sci-Fi',
      description: "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.",
    },
    {
      rank: 219,
      name: 'Jai Bhim',
      releaseDate: '2021',
      length: '2h 44m',
      rating: 8.8,
      director: 'T.J. Gnanavel',
      genre: 'Drama',
      description: "When a tribal man is arrested for a case of alleged theft, his wife turns to a human-rights lawyer to help bring justice.",
    },
    {
      rank: 220,
      name: 'Rush',
      releaseDate: '2013',
      length: '2h 3m',
      rating: 8.1,
      director: 'Ron Howard',
      genre: 'Action, Biography, Drama',
      description: "The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.",
    },
    {
      rank: 221,
      name: 'Before Sunset',
      releaseDate: '2004',
      length: '1h 20m',
      rating: 8.1,
      director: 'Richard Linklater',
      genre: 'Drama, Romance',
      description: "Nine years after Jesse and Celine first met, they encounter each other again on the French leg of Jesse's book tour.",
    },
    {
      rank: 222,
      name: 'Stand by Me',
      releaseDate: '1986',
      length: '1h 29m',
      rating: 8.1,
      director: 'Rob Reiner',
      genre: 'Adventure, Drama',
      description: "After the death of one of his friends, a writer recounts a childhood journey with his friends to find the body of a missing boy.",
    },
    {
      rank: 223,
      name: 'Network',
      releaseDate: '1976',
      length: '2h 1m',
      rating: 8.1,
      director: 'Sidney Lumet',
      genre: 'Drama',
      description: "A television network cynically exploits a deranged former anchor's ravings and revelations about the news media for its own profit, but finds that his message may be difficult to control.",
    },
    {
      rank: 224,
      name: 'Into the Wild',
      releaseDate: '2007',
      length: '2h 28m',
      rating: 8.1,
      director: 'Sean Penn',
      genre: 'Adventure, Biography, Drama',
      description: "After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity, and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.",
    },
    {
      rank: 225,
      name: 'The Wizard of Oz',
      releaseDate: '1939',
      length: '1h 42m',
      rating: 8.1,
      director: 'Victor Fleming',
      genre: 'Adventure, Family, Fantasy',
      description: "Young Dorothy Gale and her dog Toto are swept away by a tornado from their Kansas farm to the magical Land of Oz, and embark on a quest with three new friends to see the Wizard, who can return her to her home and fulfill the others' wishes.",
    },
    {
      rank: 226,
      name: 'The Best Years of Our Lives',
      releaseDate: '1946',
      length: '2h 50m',
      rating: 8.1,
      director: 'William Wyler',
      genre: 'Drama, Romance, War',
      description: "Three World War II veterans, two of them traumatized or disabled, return home to the American Midwest to discover that they and their families have been irreparably changed.",
    },
    {
      rank: 227,
      name: 'La haine',
      releaseDate: '1995',
      length: '1h 38m',
      rating: 8.1,
      director: 'Mathieu Kassovitz',
      genre: 'Crime, Drama',
      description: "24 hours in the lives of three young men in the French suburbs the day after a violent riot.",
    },
    {
      rank: 228,
      name: 'The Exorcist',
      releaseDate: '1973',
      length: '2h 2m',
      rating: 8.1,
      director: 'William Friedkin',
      genre: 'Horror',
      description: "When a teenage girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.",
    },
    {
      rank: 229,
      name: 'The Incredibles',
      releaseDate: '2004',
      length: '1h 55m',
      rating: 8.0,
      director: 'Brad Bird',
      genre: 'Animation, Action, Adventure',
      description: "While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.",
    },
    {
      rank: 230,
      name: 'Pirates of the Caribbean: The Curse of the Black Pearl',
      releaseDate: '2003',
      length: '2h 23m',
      rating: 8.1,
      director: 'Gore Verbinski',
      genre: 'Action, Adventure, Fantasy',
      description: "Blacksmith Will Turner teams up with eccentric pirate 'Captain' Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.",
    },
    {
      rank: 231,
      name: 'To Be or Not to Be',
      releaseDate: '1942',
      length: '1h 39m',
      rating: 8.2,
      director: 'Ernst Lubitsch',
      genre: 'Comedy, War',
      description: "During the Nazi occupation of Poland, an acting troupe becomes embroiled in a Polish soldier's efforts to track down a German spy.",
    },
    {
      rank: 232,
      name: 'Groundhog Day',
      releaseDate: '1993',
      length: '1h 41m',
      rating: 8.0,
      director: 'Harold Ramis',
      genre: 'Comedy, Fantasy, Romance',
      description: "A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.",
    },
    {
      rank: 233,
      name: 'My Father and My Son',
      releaseDate: '2005',
      length: '1h 52m',
      rating: 8.2,
      director: 'Çagan Irmak',
      genre: 'Drama, Family',
      description: "The family of a left-wing journalist is torn apart after the military coup of Turkey in 1980.",
    },
    {
      rank: 234,
      name: 'The Grapes of Wrath',
      releaseDate: '1940',
      length: '2h 9m',
      rating: 8.1,
      director: 'John Ford',
      genre: 'Drama, History',
      description: "An Oklahoma family, driven off their farm by the poverty and hopelessness of the Dust Bowl, joins the westward migration to California, suffering the misfortunes of the homeless in the Great Depression.",
    },
    {
      rank: 235,
      name: 'The Battle of Algiers',
      releaseDate: '1966',
      length: '2h 1m',
      rating: 8.1,
      director: 'Gillo Pontecorvo',
      genre: 'Drama, War',
      description: "In the 1950s, fear and violence escalate as the people of Algiers fight for independence from the French government.",
    },
    {
      rank: 236,
      name: "Hachi: A Dog's Tale",
      releaseDate: '2009',
      length: '1h 33m',
      rating: 8.1,
      director: 'Lasse Hallström',
      genre: 'Drama, Family',
      description: "A college professor bonds with an abandoned dog he takes into his home.",
    },
    {
      rank: 237,
      name: 'The Handmaiden',
      releaseDate: '2016',
      length: '2h 25m',
      rating: 8.1,
      director: 'Park Chan-wook',
      genre: 'Crime, Drama, Romance',
      description: "A woman is hired as a handmaiden to a Japanese heiress, but secretly she is involved in a plot to defraud her.",
    },
    {
      rank: 238,
      name: 'Pather Panchali',
      releaseDate: '1955',
      length: '2h 5m',
      rating: 8.2,
      director: 'Satyajit Ray',
      genre: 'Drama',
      description: "Impoverished priest Harihar Ray, dreaming of a better life for himself and his family, leaves his rural Bengal village in search of work.",
    },
    {
      rank: 239,
      name: 'Amores perros',
      releaseDate: '2000',
      length: '2h 34m',
      rating: 8.1,
      director: 'Alejandro G. Iñárritu',
      genre: 'Drama, Thriller',
      description: "A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life's harsh realities, all in the name of love.",
    },
    {
      rank: 240,
      name: 'Rebecca',
      releaseDate: '1940',
      length: '2h 10m',
      rating: 8.1,
      director: 'Alfred Hitchcock',
      genre: 'Drama, Mystery, Romance',
      description: "A self-conscious woman juggles adjusting to her new role as an aristocrat's wife and avoiding being intimidated by his first wife's spectral presence.",
    },
    {
    rank: 241,
    name: 'Cool Hand Luke',
    releaseDate: '1967',
    length: '2h 7m',
    rating: 8.1,
    director: 'Stuart Rosenberg',
    genre: 'Drama',
    description: 'A laid back Southern man is sentenced to two years in a rural prison, but refuses to conform.',
  },
  {
    rank: 242,
    name: 'The Sound of Music',
    releaseDate: '1965',
    length: '2h 52m',
    rating: 8.1,
    director: 'Robert Wise',
    genre: 'Biography, Drama, Family',
    description: 'A young novice is sent by her convent in 1930s Austria to become a governess to the seven children of a widowed naval officer.',
  },
  {
    rank: 243,
    name: 'The 400 Blows',
    releaseDate: '1959',
    length: '1h 39m',
    rating: 8.1,
    director: 'François Truffaut',
    genre: 'Crime, Drama',
    description: 'A young boy, left without attention, delves into a life of petty crime.',
  },
  {
    rank: 244,
    name: 'It Happened One Night',
    releaseDate: '1934',
    length: '1h 45m',
    rating: 8.1,
    director: 'Frank Capra',
    genre: 'Comedy, Romance',
    description: 'A renegade reporter trailing a young runaway heiress for a big story joins her on a bus heading from Florida to New York, and they end up stuck with each other when the bus leaves them behind at one of the stops.',
  },
  {
    rank: 245,
    name: 'Persona',
    releaseDate: '1966',
    length: '1h 25m',
    rating: 8.1,
    director: 'Ingmar Bergman',
    genre: 'Drama, Thriller',
    description: 'A nurse is put in charge of a mute actress and finds that their personae are melding together.',
  },
  {
    rank: 246,
    name: 'The Help',
    releaseDate: '2011',
    length: '2h 26m',
    rating: 8.1,
    director: 'Tate Taylor',
    genre: 'Drama',
    description: "An aspiring author during the civil rights movement of the 1960s decides to write a book detailing the African American maids' point of view on the white families for which they work, and the hardships they go through on a daily basis.",
  },
  {
    rank: 247,
    name: 'The Iron Giant',
    releaseDate: '1999',
    length: '1h 26m',
    rating: 8.1,
    director: 'Brad Bird',
    genre: 'Animation, Action, Adventure',
    description: 'A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.',
  },
  {
    rank: 248,
    name: 'Life of Brian',
    releaseDate: '1979',
    length: '1h 34m',
    rating: 8.0,
    director: 'Terry Jones',
    genre: 'Comedy',
    description: 'Born on the original Christmas in the stable next door to Jesus Christ, Brian of Nazareth spends his life being mistaken for a messiah.',
  },
  {
    rank: 249,
    name: 'Aladdin',
    releaseDate: '1992',
    length: '1h 30m',
    rating: 8.0,
    director: 'Ron Clements',
    genre: 'Animation, Adventure, Comedy',
    description: 'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.',
  },
  {
    rank: 250,
    name: 'Dances with Wolves',
    releaseDate: '1990',
    length: '3h 1m',
    rating: 8.0,
    director: 'Kevin Costner',
    genre: 'Adventure, Drama, Western',
    description: 'Lieutenant John Dunbar, assigned to a remote western Civil War outpost, finds himself engaging with a neighboring Sioux settlement, causing him to question his own purpose.',
  },
  
  ];
  
  module.exports = top250Movies;
  