const movieQuotes = [
    "Here's looking at you, kid. - Casablanca",
    "I'm the king of the world! - Titanic",
    "May the Force be with you. - Star Wars",
    "You can't handle the truth! - A Few Good Men",
    "I'll be back. - The Terminator",
    "You're gonna need a bigger boat. - Jaws",
    "Frankly, my dear, I don't give a damn. - Gone With the Wind",
    "Hasta la vista, baby. - Terminator 2: Judgment Day",
    "I feel the need — the need for speed! - Top Gun",
    "Chewie, we're home. - Star Wars: Episode VII",
    "I'm going to make him an offer he can't refuse. - The Godfather",
    "Mama always said life was like a box of chocolates. You never know what you're gonna get. - Forrest Gump",
    "We rob banks. - Bonnie and Clyde",
    "Plastics. - The Graduate",
    "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am. - On the Waterfront",
    "Not my tempo. - Whiplash",
    "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk? - Dirty Harry",
    "You had me at 'hello.' - Jerry Maguire",
    "Toto, I've got a feeling we're not in Kansas anymore. - The Wizard of Oz",
    "Today, I consider myself the luckiest man on the face of the earth. - The Pride of the Yankees",
    "If you build it, he will come. - Field of Dreams",
    "We'll always have Paris. - Casablanca",
    "Here's looking at you, kid. - Casablanca",
    "You've got red on you. - Shaun of the Dead",
    "Is it safe? - Marathon Man",
    "Wait a minute, wait a minute. You ain't heard nothin' yet! - The Jazz Singer",
    "Go ahead, make my day. - Sudden Impact",
    "Shane. Shane. Come back! - Shane",
    "Well, nobody's perfect. - Some Like It Hot",
    "Houston, we have a problem. - Apollo 13",
    "All right, Mr. DeMille, I'm ready for my close-up. - Sunset Boulevard",
    "Well, I don't want to survive. I want to live. - 12 Years a Slave",
    "Listen to them. Children of the night. What music they make. - Dracula",
    "My precious. - The Lord of the Rings: Two Towers",
    "May the Force be with you. - Star Wars",
    "I am Groot. - Guardians of the Galaxy",
    "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go! - On Golden Pond",
    "Tell 'em to go out there with all they got and win just one for the Gipper. - Knute Rockne All American",
    "Fasten your seatbelts. It's going to be a bumpy night. - All About Eve",
    "No wire hangers, ever! - Mommie Dearest",
    "Mother of mercy, is this the end of Rico? - Little Caesar",
    "A million dollars isn't cool. You know what's cool? A billion dollars. - The Social Network",
    "You talking to me? - Taxi Driver",
    "I'll have what she's having. - When Harry Met Sally",
    "You know how to whistle, don't you, Steve? You just put your lips together and blow. - To Have and Have Not",
    "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges! - The Treasure of the Sierra Madre",
    "What we've got here is failure to communicate. - Cool Hand Luke",
    "Keep your friends close, but your enemies closer. - The Godfather Part II",
    "As God is my witness, I'll never be hungry again. - Gone With the Wind",
    "Well, here's another nice mess you've gotten me into! - Sons of the Desert",
    "I love the smell of napalm in the morning. - Apocalypse Now",
    "I drink your milkshake! - There Will Be Blood",
    "Soylent Green is people! - Soylent Green",
    "Open the pod bay doors, HAL. - 2001: A Space Odyssey",
    "Love means never having to say you're sorry. - Love Story",
    "After all, tomorrow is another day! - Gone With the Wind",
    "Rosebud. - Citizen Kane",
    "Stella! Hey, Stella! - A Streetcar Named Desire",
    "Oh, Jerry, don't let's ask for the moon. We have the stars. - Now, Voyager",
    "Look at me. I'm the captain now. - Captain Phillips",
    "Made it, Ma! Top of the world! - White Heat",
    "Round up the usual suspects. - Casablanca",
    "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know. - Animal Crackers",
    "Greed, for lack of a better word, is good. - Wall Street",
    "I'm as mad as hell, and I'm not going to take this anymore! - Network",
    "Say hello to my little friend! - Scarface",
  "What a dump. - Beyond the Forest",
  "Mrs. Robinson, you're trying to seduce me. Aren't you? — The Graduate",
  "Louis, I think this is the beginning of a beautiful friendship. — Casablanca",
  "Gentlemen, you can't fight in here! This is the War Room! — Dr. Strangelove" ,
  "Of all the gin joints in all the towns in all the world, she walks into mine. — Casablanca",
  "They're here! - Poltergeist",
  "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti. — The Silence of the Lambs",
  ];
  
  module.exports = movieQuotes;
  